name: Verify Installs and Works with Swift

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch Needed Dependencies
      uses: mstksg/get-package@v1
      with:
        apt-get: graphviz openjdk-11-jdk
    - name: Try to make / build
      run: make test
